-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME ,TO_CHAR(PUBLISHED_DATE,'RRRR-MM-DD')
FROM BOOK B
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE CATEGORY LIKE '경제'
ORDER BY TO_CHAR(PUBLISHED_DATE,'RRRR-MM-DD')
;